// Generated by gencpp from file phoxi_camera/ConnectCamera.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_CONNECTCAMERA_H
#define PHOXI_CAMERA_MESSAGE_CONNECTCAMERA_H

#include <ros/service_traits.h>


#include <phoxi_camera/ConnectCameraRequest.h>
#include <phoxi_camera/ConnectCameraResponse.h>


namespace phoxi_camera
{

struct ConnectCamera
{

typedef ConnectCameraRequest Request;
typedef ConnectCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConnectCamera
} // namespace phoxi_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phoxi_camera::ConnectCamera > {
  static const char* value()
  {
    return "1ea130197b1f2a147f83501adb347895";
  }

  static const char* value(const ::phoxi_camera::ConnectCamera&) { return value(); }
};

template<>
struct DataType< ::phoxi_camera::ConnectCamera > {
  static const char* value()
  {
    return "phoxi_camera/ConnectCamera";
  }

  static const char* value(const ::phoxi_camera::ConnectCamera&) { return value(); }
};


// service_traits::MD5Sum< ::phoxi_camera::ConnectCameraRequest> should match
// service_traits::MD5Sum< ::phoxi_camera::ConnectCamera >
template<>
struct MD5Sum< ::phoxi_camera::ConnectCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::ConnectCamera >::value();
  }
  static const char* value(const ::phoxi_camera::ConnectCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::ConnectCameraRequest> should match
// service_traits::DataType< ::phoxi_camera::ConnectCamera >
template<>
struct DataType< ::phoxi_camera::ConnectCameraRequest>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::ConnectCamera >::value();
  }
  static const char* value(const ::phoxi_camera::ConnectCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phoxi_camera::ConnectCameraResponse> should match
// service_traits::MD5Sum< ::phoxi_camera::ConnectCamera >
template<>
struct MD5Sum< ::phoxi_camera::ConnectCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::ConnectCamera >::value();
  }
  static const char* value(const ::phoxi_camera::ConnectCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::ConnectCameraResponse> should match
// service_traits::DataType< ::phoxi_camera::ConnectCamera >
template<>
struct DataType< ::phoxi_camera::ConnectCameraResponse>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::ConnectCamera >::value();
  }
  static const char* value(const ::phoxi_camera::ConnectCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_CONNECTCAMERA_H
