// Generated by gencpp from file phoxi_camera/DeviceType.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_DEVICETYPE_H
#define PHOXI_CAMERA_MESSAGE_DEVICETYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phoxi_camera
{
template <class ContainerAllocator>
struct DeviceType_
{
  typedef DeviceType_<ContainerAllocator> Type;

  DeviceType_()
    : type(0)  {
    }
  DeviceType_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef int32_t _type_type;
  _type_type type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(PhoXiScanner)
  #undef PhoXiScanner
#endif
#if defined(_WIN32) && defined(PhoXiCamera)
  #undef PhoXiCamera
#endif
#if defined(_WIN32) && defined(NoValue)
  #undef NoValue
#endif

  enum {
    PhoXiScanner = 0,
    PhoXiCamera = 1,
    NoValue = 3,
  };


  typedef boost::shared_ptr< ::phoxi_camera::DeviceType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phoxi_camera::DeviceType_<ContainerAllocator> const> ConstPtr;

}; // struct DeviceType_

typedef ::phoxi_camera::DeviceType_<std::allocator<void> > DeviceType;

typedef boost::shared_ptr< ::phoxi_camera::DeviceType > DeviceTypePtr;
typedef boost::shared_ptr< ::phoxi_camera::DeviceType const> DeviceTypeConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phoxi_camera::DeviceType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phoxi_camera::DeviceType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::phoxi_camera::DeviceType_<ContainerAllocator1> & lhs, const ::phoxi_camera::DeviceType_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::phoxi_camera::DeviceType_<ContainerAllocator1> & lhs, const ::phoxi_camera::DeviceType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace phoxi_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::DeviceType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::DeviceType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::DeviceType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::DeviceType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::DeviceType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::DeviceType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phoxi_camera::DeviceType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f59591700edcd2d9a225ab5c76ace65";
  }

  static const char* value(const ::phoxi_camera::DeviceType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f59591700edcd2dULL;
  static const uint64_t static_value2 = 0x9a225ab5c76ace65ULL;
};

template<class ContainerAllocator>
struct DataType< ::phoxi_camera::DeviceType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phoxi_camera/DeviceType";
  }

  static const char* value(const ::phoxi_camera::DeviceType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phoxi_camera::DeviceType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 type\n"
"int32 PhoXiScanner = 0\n"
"int32 PhoXiCamera = 1\n"
"int32 NoValue = 3\n"
;
  }

  static const char* value(const ::phoxi_camera::DeviceType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phoxi_camera::DeviceType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeviceType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phoxi_camera::DeviceType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phoxi_camera::DeviceType_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_DEVICETYPE_H
