// Generated by gencpp from file phoxi_camera/Empty.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_EMPTY_H
#define PHOXI_CAMERA_MESSAGE_EMPTY_H

#include <ros/service_traits.h>


#include <phoxi_camera/EmptyRequest.h>
#include <phoxi_camera/EmptyResponse.h>


namespace phoxi_camera
{

struct Empty
{

typedef EmptyRequest Request;
typedef EmptyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Empty
} // namespace phoxi_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phoxi_camera::Empty > {
  static const char* value()
  {
    return "9bf829f07d795d3f9e541a07897da2c4";
  }

  static const char* value(const ::phoxi_camera::Empty&) { return value(); }
};

template<>
struct DataType< ::phoxi_camera::Empty > {
  static const char* value()
  {
    return "phoxi_camera/Empty";
  }

  static const char* value(const ::phoxi_camera::Empty&) { return value(); }
};


// service_traits::MD5Sum< ::phoxi_camera::EmptyRequest> should match
// service_traits::MD5Sum< ::phoxi_camera::Empty >
template<>
struct MD5Sum< ::phoxi_camera::EmptyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::Empty >::value();
  }
  static const char* value(const ::phoxi_camera::EmptyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::EmptyRequest> should match
// service_traits::DataType< ::phoxi_camera::Empty >
template<>
struct DataType< ::phoxi_camera::EmptyRequest>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::Empty >::value();
  }
  static const char* value(const ::phoxi_camera::EmptyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phoxi_camera::EmptyResponse> should match
// service_traits::MD5Sum< ::phoxi_camera::Empty >
template<>
struct MD5Sum< ::phoxi_camera::EmptyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::Empty >::value();
  }
  static const char* value(const ::phoxi_camera::EmptyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::EmptyResponse> should match
// service_traits::DataType< ::phoxi_camera::Empty >
template<>
struct DataType< ::phoxi_camera::EmptyResponse>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::Empty >::value();
  }
  static const char* value(const ::phoxi_camera::EmptyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_EMPTY_H
