// Generated by gencpp from file phoxi_camera/GetBoolResponse.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_GETBOOLRESPONSE_H
#define PHOXI_CAMERA_MESSAGE_GETBOOLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phoxi_camera
{
template <class ContainerAllocator>
struct GetBoolResponse_
{
  typedef GetBoolResponse_<ContainerAllocator> Type;

  GetBoolResponse_()
    : value(false)
    , message()
    , success(false)  {
    }
  GetBoolResponse_(const ContainerAllocator& _alloc)
    : value(false)
    , message(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetBoolResponse_

typedef ::phoxi_camera::GetBoolResponse_<std::allocator<void> > GetBoolResponse;

typedef boost::shared_ptr< ::phoxi_camera::GetBoolResponse > GetBoolResponsePtr;
typedef boost::shared_ptr< ::phoxi_camera::GetBoolResponse const> GetBoolResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phoxi_camera::GetBoolResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::phoxi_camera::GetBoolResponse_<ContainerAllocator1> & lhs, const ::phoxi_camera::GetBoolResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value &&
    lhs.message == rhs.message &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::phoxi_camera::GetBoolResponse_<ContainerAllocator1> & lhs, const ::phoxi_camera::GetBoolResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace phoxi_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8b1dd5c3d74b02494854ae2cb789829";
  }

  static const char* value(const ::phoxi_camera::GetBoolResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8b1dd5c3d74b024ULL;
  static const uint64_t static_value2 = 0x94854ae2cb789829ULL;
};

template<class ContainerAllocator>
struct DataType< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phoxi_camera/GetBoolResponse";
  }

  static const char* value(const ::phoxi_camera::GetBoolResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool value\n"
"string message\n"
"bool success\n"
;
  }

  static const char* value(const ::phoxi_camera::GetBoolResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.message);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBoolResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phoxi_camera::GetBoolResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phoxi_camera::GetBoolResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_GETBOOLRESPONSE_H
