// Generated by gencpp from file phoxi_camera/GetDeviceList.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_GETDEVICELIST_H
#define PHOXI_CAMERA_MESSAGE_GETDEVICELIST_H

#include <ros/service_traits.h>


#include <phoxi_camera/GetDeviceListRequest.h>
#include <phoxi_camera/GetDeviceListResponse.h>


namespace phoxi_camera
{

struct GetDeviceList
{

typedef GetDeviceListRequest Request;
typedef GetDeviceListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDeviceList
} // namespace phoxi_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phoxi_camera::GetDeviceList > {
  static const char* value()
  {
    return "ef887ca1bac751f546c7538e865ddf92";
  }

  static const char* value(const ::phoxi_camera::GetDeviceList&) { return value(); }
};

template<>
struct DataType< ::phoxi_camera::GetDeviceList > {
  static const char* value()
  {
    return "phoxi_camera/GetDeviceList";
  }

  static const char* value(const ::phoxi_camera::GetDeviceList&) { return value(); }
};


// service_traits::MD5Sum< ::phoxi_camera::GetDeviceListRequest> should match
// service_traits::MD5Sum< ::phoxi_camera::GetDeviceList >
template<>
struct MD5Sum< ::phoxi_camera::GetDeviceListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::GetDeviceList >::value();
  }
  static const char* value(const ::phoxi_camera::GetDeviceListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::GetDeviceListRequest> should match
// service_traits::DataType< ::phoxi_camera::GetDeviceList >
template<>
struct DataType< ::phoxi_camera::GetDeviceListRequest>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::GetDeviceList >::value();
  }
  static const char* value(const ::phoxi_camera::GetDeviceListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phoxi_camera::GetDeviceListResponse> should match
// service_traits::MD5Sum< ::phoxi_camera::GetDeviceList >
template<>
struct MD5Sum< ::phoxi_camera::GetDeviceListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::GetDeviceList >::value();
  }
  static const char* value(const ::phoxi_camera::GetDeviceListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::GetDeviceListResponse> should match
// service_traits::DataType< ::phoxi_camera::GetDeviceList >
template<>
struct DataType< ::phoxi_camera::GetDeviceListResponse>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::GetDeviceList >::value();
  }
  static const char* value(const ::phoxi_camera::GetDeviceListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_GETDEVICELIST_H
