// Generated by gencpp from file phoxi_camera/GetFrame.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_GETFRAME_H
#define PHOXI_CAMERA_MESSAGE_GETFRAME_H

#include <ros/service_traits.h>


#include <phoxi_camera/GetFrameRequest.h>
#include <phoxi_camera/GetFrameResponse.h>


namespace phoxi_camera
{

struct GetFrame
{

typedef GetFrameRequest Request;
typedef GetFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFrame
} // namespace phoxi_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phoxi_camera::GetFrame > {
  static const char* value()
  {
    return "51ed6a27e8851d6116d5fe59ddb47078";
  }

  static const char* value(const ::phoxi_camera::GetFrame&) { return value(); }
};

template<>
struct DataType< ::phoxi_camera::GetFrame > {
  static const char* value()
  {
    return "phoxi_camera/GetFrame";
  }

  static const char* value(const ::phoxi_camera::GetFrame&) { return value(); }
};


// service_traits::MD5Sum< ::phoxi_camera::GetFrameRequest> should match
// service_traits::MD5Sum< ::phoxi_camera::GetFrame >
template<>
struct MD5Sum< ::phoxi_camera::GetFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::GetFrame >::value();
  }
  static const char* value(const ::phoxi_camera::GetFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::GetFrameRequest> should match
// service_traits::DataType< ::phoxi_camera::GetFrame >
template<>
struct DataType< ::phoxi_camera::GetFrameRequest>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::GetFrame >::value();
  }
  static const char* value(const ::phoxi_camera::GetFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phoxi_camera::GetFrameResponse> should match
// service_traits::MD5Sum< ::phoxi_camera::GetFrame >
template<>
struct MD5Sum< ::phoxi_camera::GetFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::GetFrame >::value();
  }
  static const char* value(const ::phoxi_camera::GetFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::GetFrameResponse> should match
// service_traits::DataType< ::phoxi_camera::GetFrame >
template<>
struct DataType< ::phoxi_camera::GetFrameResponse>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::GetFrame >::value();
  }
  static const char* value(const ::phoxi_camera::GetFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_GETFRAME_H
