// Generated by gencpp from file phoxi_camera/GetHardwareIdentification.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_GETHARDWAREIDENTIFICATION_H
#define PHOXI_CAMERA_MESSAGE_GETHARDWAREIDENTIFICATION_H

#include <ros/service_traits.h>


#include <phoxi_camera/GetHardwareIdentificationRequest.h>
#include <phoxi_camera/GetHardwareIdentificationResponse.h>


namespace phoxi_camera
{

struct GetHardwareIdentification
{

typedef GetHardwareIdentificationRequest Request;
typedef GetHardwareIdentificationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHardwareIdentification
} // namespace phoxi_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phoxi_camera::GetHardwareIdentification > {
  static const char* value()
  {
    return "7c34903a74c1048da945ec8ca8cfa315";
  }

  static const char* value(const ::phoxi_camera::GetHardwareIdentification&) { return value(); }
};

template<>
struct DataType< ::phoxi_camera::GetHardwareIdentification > {
  static const char* value()
  {
    return "phoxi_camera/GetHardwareIdentification";
  }

  static const char* value(const ::phoxi_camera::GetHardwareIdentification&) { return value(); }
};


// service_traits::MD5Sum< ::phoxi_camera::GetHardwareIdentificationRequest> should match
// service_traits::MD5Sum< ::phoxi_camera::GetHardwareIdentification >
template<>
struct MD5Sum< ::phoxi_camera::GetHardwareIdentificationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::GetHardwareIdentification >::value();
  }
  static const char* value(const ::phoxi_camera::GetHardwareIdentificationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::GetHardwareIdentificationRequest> should match
// service_traits::DataType< ::phoxi_camera::GetHardwareIdentification >
template<>
struct DataType< ::phoxi_camera::GetHardwareIdentificationRequest>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::GetHardwareIdentification >::value();
  }
  static const char* value(const ::phoxi_camera::GetHardwareIdentificationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phoxi_camera::GetHardwareIdentificationResponse> should match
// service_traits::MD5Sum< ::phoxi_camera::GetHardwareIdentification >
template<>
struct MD5Sum< ::phoxi_camera::GetHardwareIdentificationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::GetHardwareIdentification >::value();
  }
  static const char* value(const ::phoxi_camera::GetHardwareIdentificationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::GetHardwareIdentificationResponse> should match
// service_traits::DataType< ::phoxi_camera::GetHardwareIdentification >
template<>
struct DataType< ::phoxi_camera::GetHardwareIdentificationResponse>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::GetHardwareIdentification >::value();
  }
  static const char* value(const ::phoxi_camera::GetHardwareIdentificationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_GETHARDWAREIDENTIFICATION_H
