// Generated by gencpp from file phoxi_camera/GetString.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_GETSTRING_H
#define PHOXI_CAMERA_MESSAGE_GETSTRING_H

#include <ros/service_traits.h>


#include <phoxi_camera/GetStringRequest.h>
#include <phoxi_camera/GetStringResponse.h>


namespace phoxi_camera
{

struct GetString
{

typedef GetStringRequest Request;
typedef GetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetString
} // namespace phoxi_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phoxi_camera::GetString > {
  static const char* value()
  {
    return "433bf658b0146fb6dd240f5d5c05b01c";
  }

  static const char* value(const ::phoxi_camera::GetString&) { return value(); }
};

template<>
struct DataType< ::phoxi_camera::GetString > {
  static const char* value()
  {
    return "phoxi_camera/GetString";
  }

  static const char* value(const ::phoxi_camera::GetString&) { return value(); }
};


// service_traits::MD5Sum< ::phoxi_camera::GetStringRequest> should match
// service_traits::MD5Sum< ::phoxi_camera::GetString >
template<>
struct MD5Sum< ::phoxi_camera::GetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::GetString >::value();
  }
  static const char* value(const ::phoxi_camera::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::GetStringRequest> should match
// service_traits::DataType< ::phoxi_camera::GetString >
template<>
struct DataType< ::phoxi_camera::GetStringRequest>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::GetString >::value();
  }
  static const char* value(const ::phoxi_camera::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phoxi_camera::GetStringResponse> should match
// service_traits::MD5Sum< ::phoxi_camera::GetString >
template<>
struct MD5Sum< ::phoxi_camera::GetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::GetString >::value();
  }
  static const char* value(const ::phoxi_camera::GetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::GetStringResponse> should match
// service_traits::DataType< ::phoxi_camera::GetString >
template<>
struct DataType< ::phoxi_camera::GetStringResponse>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::GetString >::value();
  }
  static const char* value(const ::phoxi_camera::GetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_GETSTRING_H
