// Generated by gencpp from file phoxi_camera/IsAcquiringResponse.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_ISACQUIRINGRESPONSE_H
#define PHOXI_CAMERA_MESSAGE_ISACQUIRINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phoxi_camera
{
template <class ContainerAllocator>
struct IsAcquiringResponse_
{
  typedef IsAcquiringResponse_<ContainerAllocator> Type;

  IsAcquiringResponse_()
    : is_acquiring(false)  {
    }
  IsAcquiringResponse_(const ContainerAllocator& _alloc)
    : is_acquiring(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_acquiring_type;
  _is_acquiring_type is_acquiring;





  typedef boost::shared_ptr< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IsAcquiringResponse_

typedef ::phoxi_camera::IsAcquiringResponse_<std::allocator<void> > IsAcquiringResponse;

typedef boost::shared_ptr< ::phoxi_camera::IsAcquiringResponse > IsAcquiringResponsePtr;
typedef boost::shared_ptr< ::phoxi_camera::IsAcquiringResponse const> IsAcquiringResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator1> & lhs, const ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_acquiring == rhs.is_acquiring;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator1> & lhs, const ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace phoxi_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "178c4f223aa32769d3555a15bcb0158f";
  }

  static const char* value(const ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x178c4f223aa32769ULL;
  static const uint64_t static_value2 = 0xd3555a15bcb0158fULL;
};

template<class ContainerAllocator>
struct DataType< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phoxi_camera/IsAcquiringResponse";
  }

  static const char* value(const ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_acquiring\n"
;
  }

  static const char* value(const ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_acquiring);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsAcquiringResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phoxi_camera::IsAcquiringResponse_<ContainerAllocator>& v)
  {
    s << indent << "is_acquiring: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_acquiring);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_ISACQUIRINGRESPONSE_H
