// Generated by gencpp from file phoxi_camera/IsAcquiring.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_ISACQUIRING_H
#define PHOXI_CAMERA_MESSAGE_ISACQUIRING_H

#include <ros/service_traits.h>


#include <phoxi_camera/IsAcquiringRequest.h>
#include <phoxi_camera/IsAcquiringResponse.h>


namespace phoxi_camera
{

struct IsAcquiring
{

typedef IsAcquiringRequest Request;
typedef IsAcquiringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsAcquiring
} // namespace phoxi_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phoxi_camera::IsAcquiring > {
  static const char* value()
  {
    return "178c4f223aa32769d3555a15bcb0158f";
  }

  static const char* value(const ::phoxi_camera::IsAcquiring&) { return value(); }
};

template<>
struct DataType< ::phoxi_camera::IsAcquiring > {
  static const char* value()
  {
    return "phoxi_camera/IsAcquiring";
  }

  static const char* value(const ::phoxi_camera::IsAcquiring&) { return value(); }
};


// service_traits::MD5Sum< ::phoxi_camera::IsAcquiringRequest> should match
// service_traits::MD5Sum< ::phoxi_camera::IsAcquiring >
template<>
struct MD5Sum< ::phoxi_camera::IsAcquiringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::IsAcquiring >::value();
  }
  static const char* value(const ::phoxi_camera::IsAcquiringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::IsAcquiringRequest> should match
// service_traits::DataType< ::phoxi_camera::IsAcquiring >
template<>
struct DataType< ::phoxi_camera::IsAcquiringRequest>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::IsAcquiring >::value();
  }
  static const char* value(const ::phoxi_camera::IsAcquiringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phoxi_camera::IsAcquiringResponse> should match
// service_traits::MD5Sum< ::phoxi_camera::IsAcquiring >
template<>
struct MD5Sum< ::phoxi_camera::IsAcquiringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::IsAcquiring >::value();
  }
  static const char* value(const ::phoxi_camera::IsAcquiringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::IsAcquiringResponse> should match
// service_traits::DataType< ::phoxi_camera::IsAcquiring >
template<>
struct DataType< ::phoxi_camera::IsAcquiringResponse>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::IsAcquiring >::value();
  }
  static const char* value(const ::phoxi_camera::IsAcquiringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_ISACQUIRING_H
