// Generated by gencpp from file phoxi_camera/IsConnectedResponse.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_ISCONNECTEDRESPONSE_H
#define PHOXI_CAMERA_MESSAGE_ISCONNECTEDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phoxi_camera
{
template <class ContainerAllocator>
struct IsConnectedResponse_
{
  typedef IsConnectedResponse_<ContainerAllocator> Type;

  IsConnectedResponse_()
    : connected(false)  {
    }
  IsConnectedResponse_(const ContainerAllocator& _alloc)
    : connected(false)  {
  (void)_alloc;
    }



   typedef uint8_t _connected_type;
  _connected_type connected;





  typedef boost::shared_ptr< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IsConnectedResponse_

typedef ::phoxi_camera::IsConnectedResponse_<std::allocator<void> > IsConnectedResponse;

typedef boost::shared_ptr< ::phoxi_camera::IsConnectedResponse > IsConnectedResponsePtr;
typedef boost::shared_ptr< ::phoxi_camera::IsConnectedResponse const> IsConnectedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::phoxi_camera::IsConnectedResponse_<ContainerAllocator1> & lhs, const ::phoxi_camera::IsConnectedResponse_<ContainerAllocator2> & rhs)
{
  return lhs.connected == rhs.connected;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::phoxi_camera::IsConnectedResponse_<ContainerAllocator1> & lhs, const ::phoxi_camera::IsConnectedResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace phoxi_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0cdaf65159c7f3563426650fb8d3f64";
  }

  static const char* value(const ::phoxi_camera::IsConnectedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0cdaf65159c7f35ULL;
  static const uint64_t static_value2 = 0x63426650fb8d3f64ULL;
};

template<class ContainerAllocator>
struct DataType< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phoxi_camera/IsConnectedResponse";
  }

  static const char* value(const ::phoxi_camera::IsConnectedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool connected\n"
;
  }

  static const char* value(const ::phoxi_camera::IsConnectedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.connected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsConnectedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phoxi_camera::IsConnectedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phoxi_camera::IsConnectedResponse_<ContainerAllocator>& v)
  {
    s << indent << "connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_ISCONNECTEDRESPONSE_H
