// Generated by gencpp from file phoxi_camera/PhoXiSize.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_PHOXISIZE_H
#define PHOXI_CAMERA_MESSAGE_PHOXISIZE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phoxi_camera
{
template <class ContainerAllocator>
struct PhoXiSize_
{
  typedef PhoXiSize_<ContainerAllocator> Type;

  PhoXiSize_()
    : Width(0)
    , Height(0)  {
    }
  PhoXiSize_(const ContainerAllocator& _alloc)
    : Width(0)
    , Height(0)  {
  (void)_alloc;
    }



   typedef int32_t _Width_type;
  _Width_type Width;

   typedef int32_t _Height_type;
  _Height_type Height;





  typedef boost::shared_ptr< ::phoxi_camera::PhoXiSize_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phoxi_camera::PhoXiSize_<ContainerAllocator> const> ConstPtr;

}; // struct PhoXiSize_

typedef ::phoxi_camera::PhoXiSize_<std::allocator<void> > PhoXiSize;

typedef boost::shared_ptr< ::phoxi_camera::PhoXiSize > PhoXiSizePtr;
typedef boost::shared_ptr< ::phoxi_camera::PhoXiSize const> PhoXiSizeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phoxi_camera::PhoXiSize_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phoxi_camera::PhoXiSize_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::phoxi_camera::PhoXiSize_<ContainerAllocator1> & lhs, const ::phoxi_camera::PhoXiSize_<ContainerAllocator2> & rhs)
{
  return lhs.Width == rhs.Width &&
    lhs.Height == rhs.Height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::phoxi_camera::PhoXiSize_<ContainerAllocator1> & lhs, const ::phoxi_camera::PhoXiSize_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace phoxi_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::PhoXiSize_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::PhoXiSize_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::PhoXiSize_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::PhoXiSize_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::PhoXiSize_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::PhoXiSize_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phoxi_camera::PhoXiSize_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe4516275dcf5be9aa7db57236a062a6";
  }

  static const char* value(const ::phoxi_camera::PhoXiSize_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe4516275dcf5be9ULL;
  static const uint64_t static_value2 = 0xaa7db57236a062a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::phoxi_camera::PhoXiSize_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phoxi_camera/PhoXiSize";
  }

  static const char* value(const ::phoxi_camera::PhoXiSize_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phoxi_camera::PhoXiSize_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Width\n"
"int32 Height\n"
;
  }

  static const char* value(const ::phoxi_camera::PhoXiSize_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phoxi_camera::PhoXiSize_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Width);
      stream.next(m.Height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PhoXiSize_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phoxi_camera::PhoXiSize_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phoxi_camera::PhoXiSize_<ContainerAllocator>& v)
  {
    s << indent << "Width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Width);
    s << indent << "Height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_PHOXISIZE_H
