// Generated by gencpp from file phoxi_camera/SaveFrame.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_SAVEFRAME_H
#define PHOXI_CAMERA_MESSAGE_SAVEFRAME_H

#include <ros/service_traits.h>


#include <phoxi_camera/SaveFrameRequest.h>
#include <phoxi_camera/SaveFrameResponse.h>


namespace phoxi_camera
{

struct SaveFrame
{

typedef SaveFrameRequest Request;
typedef SaveFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveFrame
} // namespace phoxi_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phoxi_camera::SaveFrame > {
  static const char* value()
  {
    return "7dde036917924a72a5bcf22d6795b22c";
  }

  static const char* value(const ::phoxi_camera::SaveFrame&) { return value(); }
};

template<>
struct DataType< ::phoxi_camera::SaveFrame > {
  static const char* value()
  {
    return "phoxi_camera/SaveFrame";
  }

  static const char* value(const ::phoxi_camera::SaveFrame&) { return value(); }
};


// service_traits::MD5Sum< ::phoxi_camera::SaveFrameRequest> should match
// service_traits::MD5Sum< ::phoxi_camera::SaveFrame >
template<>
struct MD5Sum< ::phoxi_camera::SaveFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::SaveFrame >::value();
  }
  static const char* value(const ::phoxi_camera::SaveFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::SaveFrameRequest> should match
// service_traits::DataType< ::phoxi_camera::SaveFrame >
template<>
struct DataType< ::phoxi_camera::SaveFrameRequest>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::SaveFrame >::value();
  }
  static const char* value(const ::phoxi_camera::SaveFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phoxi_camera::SaveFrameResponse> should match
// service_traits::MD5Sum< ::phoxi_camera::SaveFrame >
template<>
struct MD5Sum< ::phoxi_camera::SaveFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::SaveFrame >::value();
  }
  static const char* value(const ::phoxi_camera::SaveFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::SaveFrameResponse> should match
// service_traits::DataType< ::phoxi_camera::SaveFrame >
template<>
struct DataType< ::phoxi_camera::SaveFrameResponse>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::SaveFrame >::value();
  }
  static const char* value(const ::phoxi_camera::SaveFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_SAVEFRAME_H
