// Generated by gencpp from file phoxi_camera/SetCoordinatesSpace.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_SETCOORDINATESSPACE_H
#define PHOXI_CAMERA_MESSAGE_SETCOORDINATESSPACE_H

#include <ros/service_traits.h>


#include <phoxi_camera/SetCoordinatesSpaceRequest.h>
#include <phoxi_camera/SetCoordinatesSpaceResponse.h>


namespace phoxi_camera
{

struct SetCoordinatesSpace
{

typedef SetCoordinatesSpaceRequest Request;
typedef SetCoordinatesSpaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCoordinatesSpace
} // namespace phoxi_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phoxi_camera::SetCoordinatesSpace > {
  static const char* value()
  {
    return "6471d6222bbb561b60df31b08bec6e6d";
  }

  static const char* value(const ::phoxi_camera::SetCoordinatesSpace&) { return value(); }
};

template<>
struct DataType< ::phoxi_camera::SetCoordinatesSpace > {
  static const char* value()
  {
    return "phoxi_camera/SetCoordinatesSpace";
  }

  static const char* value(const ::phoxi_camera::SetCoordinatesSpace&) { return value(); }
};


// service_traits::MD5Sum< ::phoxi_camera::SetCoordinatesSpaceRequest> should match
// service_traits::MD5Sum< ::phoxi_camera::SetCoordinatesSpace >
template<>
struct MD5Sum< ::phoxi_camera::SetCoordinatesSpaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::SetCoordinatesSpace >::value();
  }
  static const char* value(const ::phoxi_camera::SetCoordinatesSpaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::SetCoordinatesSpaceRequest> should match
// service_traits::DataType< ::phoxi_camera::SetCoordinatesSpace >
template<>
struct DataType< ::phoxi_camera::SetCoordinatesSpaceRequest>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::SetCoordinatesSpace >::value();
  }
  static const char* value(const ::phoxi_camera::SetCoordinatesSpaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phoxi_camera::SetCoordinatesSpaceResponse> should match
// service_traits::MD5Sum< ::phoxi_camera::SetCoordinatesSpace >
template<>
struct MD5Sum< ::phoxi_camera::SetCoordinatesSpaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::SetCoordinatesSpace >::value();
  }
  static const char* value(const ::phoxi_camera::SetCoordinatesSpaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::SetCoordinatesSpaceResponse> should match
// service_traits::DataType< ::phoxi_camera::SetCoordinatesSpace >
template<>
struct DataType< ::phoxi_camera::SetCoordinatesSpaceResponse>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::SetCoordinatesSpace >::value();
  }
  static const char* value(const ::phoxi_camera::SetCoordinatesSpaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_SETCOORDINATESSPACE_H
