// Generated by gencpp from file phoxi_camera/SetCoordinatesSpaceRequest.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_SETCOORDINATESSPACEREQUEST_H
#define PHOXI_CAMERA_MESSAGE_SETCOORDINATESSPACEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phoxi_camera
{
template <class ContainerAllocator>
struct SetCoordinatesSpaceRequest_
{
  typedef SetCoordinatesSpaceRequest_<ContainerAllocator> Type;

  SetCoordinatesSpaceRequest_()
    : coordinates_space(0)  {
    }
  SetCoordinatesSpaceRequest_(const ContainerAllocator& _alloc)
    : coordinates_space(0)  {
  (void)_alloc;
    }



   typedef uint8_t _coordinates_space_type;
  _coordinates_space_type coordinates_space;





  typedef boost::shared_ptr< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCoordinatesSpaceRequest_

typedef ::phoxi_camera::SetCoordinatesSpaceRequest_<std::allocator<void> > SetCoordinatesSpaceRequest;

typedef boost::shared_ptr< ::phoxi_camera::SetCoordinatesSpaceRequest > SetCoordinatesSpaceRequestPtr;
typedef boost::shared_ptr< ::phoxi_camera::SetCoordinatesSpaceRequest const> SetCoordinatesSpaceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator1> & lhs, const ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.coordinates_space == rhs.coordinates_space;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator1> & lhs, const ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace phoxi_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb29d6a290d76876ae055943fb930516";
  }

  static const char* value(const ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb29d6a290d76876ULL;
  static const uint64_t static_value2 = 0xae055943fb930516ULL;
};

template<class ContainerAllocator>
struct DataType< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phoxi_camera/SetCoordinatesSpaceRequest";
  }

  static const char* value(const ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 coordinates_space  # NoValue = 0, CameraSpace = 1, MarkerSpace = 3, RobotSpace = 4, CustomSpace = 5\n"
;
  }

  static const char* value(const ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coordinates_space);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCoordinatesSpaceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phoxi_camera::SetCoordinatesSpaceRequest_<ContainerAllocator>& v)
  {
    s << indent << "coordinates_space: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.coordinates_space);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_SETCOORDINATESSPACEREQUEST_H
