// Generated by gencpp from file phoxi_camera/SetTransformationMatrix.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_SETTRANSFORMATIONMATRIX_H
#define PHOXI_CAMERA_MESSAGE_SETTRANSFORMATIONMATRIX_H

#include <ros/service_traits.h>


#include <phoxi_camera/SetTransformationMatrixRequest.h>
#include <phoxi_camera/SetTransformationMatrixResponse.h>


namespace phoxi_camera
{

struct SetTransformationMatrix
{

typedef SetTransformationMatrixRequest Request;
typedef SetTransformationMatrixResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTransformationMatrix
} // namespace phoxi_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phoxi_camera::SetTransformationMatrix > {
  static const char* value()
  {
    return "451cc6edd533358f5a507561ee1fbaee";
  }

  static const char* value(const ::phoxi_camera::SetTransformationMatrix&) { return value(); }
};

template<>
struct DataType< ::phoxi_camera::SetTransformationMatrix > {
  static const char* value()
  {
    return "phoxi_camera/SetTransformationMatrix";
  }

  static const char* value(const ::phoxi_camera::SetTransformationMatrix&) { return value(); }
};


// service_traits::MD5Sum< ::phoxi_camera::SetTransformationMatrixRequest> should match
// service_traits::MD5Sum< ::phoxi_camera::SetTransformationMatrix >
template<>
struct MD5Sum< ::phoxi_camera::SetTransformationMatrixRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::SetTransformationMatrix >::value();
  }
  static const char* value(const ::phoxi_camera::SetTransformationMatrixRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::SetTransformationMatrixRequest> should match
// service_traits::DataType< ::phoxi_camera::SetTransformationMatrix >
template<>
struct DataType< ::phoxi_camera::SetTransformationMatrixRequest>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::SetTransformationMatrix >::value();
  }
  static const char* value(const ::phoxi_camera::SetTransformationMatrixRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phoxi_camera::SetTransformationMatrixResponse> should match
// service_traits::MD5Sum< ::phoxi_camera::SetTransformationMatrix >
template<>
struct MD5Sum< ::phoxi_camera::SetTransformationMatrixResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phoxi_camera::SetTransformationMatrix >::value();
  }
  static const char* value(const ::phoxi_camera::SetTransformationMatrixResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phoxi_camera::SetTransformationMatrixResponse> should match
// service_traits::DataType< ::phoxi_camera::SetTransformationMatrix >
template<>
struct DataType< ::phoxi_camera::SetTransformationMatrixResponse>
{
  static const char* value()
  {
    return DataType< ::phoxi_camera::SetTransformationMatrix >::value();
  }
  static const char* value(const ::phoxi_camera::SetTransformationMatrixResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_SETTRANSFORMATIONMATRIX_H
