// Generated by gencpp from file phoxi_camera/TriggerImageRequest.msg
// DO NOT EDIT!


#ifndef PHOXI_CAMERA_MESSAGE_TRIGGERIMAGEREQUEST_H
#define PHOXI_CAMERA_MESSAGE_TRIGGERIMAGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phoxi_camera
{
template <class ContainerAllocator>
struct TriggerImageRequest_
{
  typedef TriggerImageRequest_<ContainerAllocator> Type;

  TriggerImageRequest_()
    {
    }
  TriggerImageRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerImageRequest_

typedef ::phoxi_camera::TriggerImageRequest_<std::allocator<void> > TriggerImageRequest;

typedef boost::shared_ptr< ::phoxi_camera::TriggerImageRequest > TriggerImageRequestPtr;
typedef boost::shared_ptr< ::phoxi_camera::TriggerImageRequest const> TriggerImageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace phoxi_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::phoxi_camera::TriggerImageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phoxi_camera/TriggerImageRequest";
  }

  static const char* value(const ::phoxi_camera::TriggerImageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::phoxi_camera::TriggerImageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerImageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phoxi_camera::TriggerImageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::phoxi_camera::TriggerImageRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PHOXI_CAMERA_MESSAGE_TRIGGERIMAGEREQUEST_H
