controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
  # - name: gripper_controller
  #   type: GripperCommand
  #   action_ns: gripper_action
  #   default: true
  #   parallel: true
  #   joints: [joint_l_finger, joint_r_finger]