scanner_id: "2018-11-032-LC3" # keep "" if scanner id is number
frame_id: "PhoXi3Dscanner_sensor"
latch_topics: false
topic_queue_size: 1
init_from_config: false # if true all following parameters will be initialized from this config otherwise from PhoXi control application.
organized_cloud: true # if true organized point cloud will be published, other otherwise unorganized (Default value true)

# All following parameters are for PhoXi Control and they can override all dynamic_reconfigure parameters in cfg file.
# This values are set to scanner after successful connection only if init_from_config parameter is true.
resolution: 1         # 0 = Low, 1 = High
scan_multiplier: 1
confidence: 3.0
send_confidence_map: true
send_depth_map: true
send_normal_map: true
send_point_cloud: true
send_texture: true
shutter_multiplier: 1
timeout: -3          # in ms, special parameters: 0 = Zero, -1 = Infinity, -2 = Last stored, -3 = Default
trigger_mode: 1      # 0 = Free run, 1 = Software

## Setting available only for PhoXi Control 1.2 and higher. Also for dynamic reconfigure
coordinate_space: 1 # 1 = Camera, 2 =  Mounting, 3 = Marker, 4 = Robot, 5 = Custom
ambient_light_suppression: false  # Ambient light suppression samples the scene multiple times during one pattern exposure.
                                  # This multiple samples are then used to suppress the effect of ambient illumination by eliminating most of the shot noise caused by longer exposure of ambient light.
                                  # Enabling the mode will set Shutter multiplier to fixed value of 2.
single_pattern_exposure: 2    # The time for projection of one pattern. Use only provided values form PhoXi control settings!
                              # 0 = 10.240; 1 = 14.336; 2 = 20.480; 3 = 24.576; 4 = 30.720;  5 = 34.816;
                              # 6 = 40.960; 7 = 49.152; 8 = 75.776; 9 = 79.872; 10 = 90.112; 11 = 100.352
camera_only_mode: false       # With this mode you can use the scanner internal camera to capture only 2D images of the scene.
