(cl:defpackage phoxi_camera-msg
  (:use )
  (:export
   "<DEVICECONNECTIONSTATUS>"
   "DEVICECONNECTIONSTATUS"
   "<DEVICEINFORMATION>"
   "DEVICEINFORMATION"
   "<DEVICETYPE>"
   "DEVICETYPE"
   "<PHOXISIZE>"
   "PHOXISIZE"
  ))

